-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE nexaboard_thread (
  nbt_id BIGSERIAL NOT NULL,
  nbt_board_user_id INT NOT NULL,
  nbt_title TEXT NOT NULL,
  nbt_status SMALLINT DEFAULT 0 NOT NULL,
  nbt_reply_count INT DEFAULT 0 NOT NULL,
  nbt_created TIMESTAMPTZ NOT NULL,
  nbt_updated TIMESTAMPTZ NOT NULL,
  nbt_closed_by INT DEFAULT NULL,
  nbt_deleted_by INT DEFAULT NULL,
  nbt_merged_into BIGINT DEFAULT NULL,
  PRIMARY KEY(nbt_id)
);

CREATE INDEX nbt_board ON nexaboard_thread (
  nbt_board_user_id, nbt_status, nbt_updated
);

CREATE INDEX nbt_merged ON nexaboard_thread (nbt_merged_into);


CREATE TABLE nexaboard_message (
  nbm_id BIGSERIAL NOT NULL,
  nbm_thread_id BIGINT NOT NULL,
  nbm_is_op SMALLINT DEFAULT 0 NOT NULL,
  nbm_parent_id BIGINT DEFAULT NULL,
  nbm_author_id INT NOT NULL,
  nbm_author_name TEXT NOT NULL,
  nbm_body TEXT NOT NULL,
  nbm_quote_id BIGINT DEFAULT NULL,
  nbm_created TIMESTAMPTZ NOT NULL,
  nbm_edited TIMESTAMPTZ DEFAULT NULL,
  nbm_deleted SMALLINT DEFAULT 0 NOT NULL,
  nbm_deleted_by INT DEFAULT NULL,
  PRIMARY KEY(nbm_id)
);

CREATE INDEX nbm_thread ON nexaboard_message (
  nbm_thread_id, nbm_deleted, nbm_created
);

CREATE INDEX nbm_parent ON nexaboard_message (nbm_parent_id);

CREATE INDEX nbm_author ON nexaboard_message (nbm_author_id);

CREATE INDEX nbm_quote ON nexaboard_message (nbm_quote_id);


CREATE TABLE nexaboard_follow (
  nbf_thread_id BIGINT NOT NULL,
  nbf_user_id INT NOT NULL,
  nbf_muted SMALLINT DEFAULT 0 NOT NULL,
  nbf_created TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(nbf_thread_id, nbf_user_id)
);

CREATE INDEX nbf_user ON nexaboard_follow (nbf_user_id, nbf_thread_id);
