-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/nexaboard_thread (
  nbt_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  nbt_board_user_id INTEGER UNSIGNED NOT NULL,
  nbt_title BLOB NOT NULL, nbt_status SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  nbt_reply_count INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  nbt_created BLOB NOT NULL, nbt_updated BLOB NOT NULL,
  nbt_closed_by INTEGER UNSIGNED DEFAULT NULL,
  nbt_deleted_by INTEGER UNSIGNED DEFAULT NULL,
  nbt_merged_into BIGINT UNSIGNED DEFAULT NULL
);

CREATE INDEX nbt_board ON /*_*/nexaboard_thread (
  nbt_board_user_id, nbt_status, nbt_updated
);

CREATE INDEX nbt_merged ON /*_*/nexaboard_thread (nbt_merged_into);


CREATE TABLE /*_*/nexaboard_message (
  nbm_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  nbm_thread_id BIGINT UNSIGNED NOT NULL,
  nbm_is_op SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  nbm_parent_id BIGINT UNSIGNED DEFAULT NULL,
  nbm_author_id INTEGER UNSIGNED NOT NULL,
  nbm_author_name BLOB NOT NULL, nbm_body BLOB NOT NULL,
  nbm_quote_id BIGINT UNSIGNED DEFAULT NULL,
  nbm_created BLOB NOT NULL, nbm_edited BLOB DEFAULT NULL,
  nbm_deleted SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  nbm_deleted_by INTEGER UNSIGNED DEFAULT NULL
);

CREATE INDEX nbm_thread ON /*_*/nexaboard_message (
  nbm_thread_id, nbm_deleted, nbm_created
);

CREATE INDEX nbm_parent ON /*_*/nexaboard_message (nbm_parent_id);

CREATE INDEX nbm_author ON /*_*/nexaboard_message (nbm_author_id);

CREATE INDEX nbm_quote ON /*_*/nexaboard_message (nbm_quote_id);


CREATE TABLE /*_*/nexaboard_follow (
  nbf_thread_id BIGINT UNSIGNED NOT NULL,
  nbf_user_id INTEGER UNSIGNED NOT NULL,
  nbf_muted SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  nbf_created BLOB NOT NULL,
  PRIMARY KEY(nbf_thread_id, nbf_user_id)
);

CREATE INDEX nbf_user ON /*_*/nexaboard_follow (nbf_user_id, nbf_thread_id);
