-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/nexaboard_thread (
  nbt_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  nbt_board_user_id INT UNSIGNED NOT NULL,
  nbt_title VARBINARY(800) NOT NULL,
  nbt_status TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  nbt_reply_count INT UNSIGNED DEFAULT 0 NOT NULL,
  nbt_created BINARY(14) NOT NULL,
  nbt_updated BINARY(14) NOT NULL,
  nbt_closed_by INT UNSIGNED DEFAULT NULL,
  nbt_deleted_by INT UNSIGNED DEFAULT NULL,
  nbt_merged_into BIGINT UNSIGNED DEFAULT NULL,
  INDEX nbt_board (
    nbt_board_user_id, nbt_status, nbt_updated
  ),
  INDEX nbt_merged (nbt_merged_into),
  PRIMARY KEY(nbt_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/nexaboard_message (
  nbm_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  nbm_thread_id BIGINT UNSIGNED NOT NULL,
  nbm_is_op TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  nbm_parent_id BIGINT UNSIGNED DEFAULT NULL,
  nbm_author_id INT UNSIGNED NOT NULL,
  nbm_author_name VARBINARY(255) NOT NULL,
  nbm_body MEDIUMBLOB NOT NULL,
  nbm_quote_id BIGINT UNSIGNED DEFAULT NULL,
  nbm_created BINARY(14) NOT NULL,
  nbm_edited BINARY(14) DEFAULT NULL,
  nbm_edited_by INT UNSIGNED DEFAULT NULL,
  nbm_deleted TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  nbm_deleted_by INT UNSIGNED DEFAULT NULL,
  INDEX nbm_thread (
    nbm_thread_id, nbm_deleted, nbm_created
  ),
  INDEX nbm_parent (nbm_parent_id),
  INDEX nbm_author (nbm_author_id),
  INDEX nbm_quote (nbm_quote_id),
  PRIMARY KEY(nbm_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/nexaboard_follow (
  nbf_thread_id BIGINT UNSIGNED NOT NULL,
  nbf_user_id INT UNSIGNED NOT NULL,
  nbf_muted TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  nbf_created BINARY(14) NOT NULL,
  INDEX nbf_user (nbf_user_id, nbf_thread_id),
  PRIMARY KEY(nbf_thread_id, nbf_user_id)
) /*$wgDBTableOptions*/;
